host: "127.0.0.1"
port: 8080
static_root: "static"
log_file: "logs/access.log"
debug: false  # to print deug message
error: false  # to print error message
clear_log : true  # clear log on fresh start
worker: 4

upstream:
  - mainweb:
    - "127.0.0.1:5000"
    - "127.0.0.1:5000"

routes:
  - path: "/static"
    type: "static"
    file: "index.html"

  - path: "/hello"
    type: "response"
    message: "Response message: Welcome to Mini-Nginx"

  - path: "/"
    type: "proxy"
    target: "127.0.0.1:5000"

  - path: "/upstream"
    type: "upstream"
    upstream: "mainweb"
